### ISSUE TITLE
Exception: Could not find all species in the subquery. This should not happen.

### ISSUE THREAD

**Issue by ShiQiaoL** [romankempt/hetbuilder#13]
`
bottom = ase.io.read("Optimized-structure-20240506/Al2ZnS4-2dm-3208.vasp")
top = ase.io.read("Optimized-structure-20240506/MoS2-2dm-3150.vasp")
alg = CoincidenceAlgorithm(bottom, top)
results = alg.run(Nmax=20,
                           Nmin=0, angles = [0, 10, 15, 20], 
                          weight=0.5,
                          angle_stepsize=0.05,
                          tolerance=0.1,
                          distance=3.0)
`
> WARNING  It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True,  
         False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0,   
         0.0, 100.0]]) is not primitive.                                        
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  atom_checks          check_if_primitive   |
 It seems that the structure Atoms(symbols='Al2ZnS4', pbc=[True, True, False], cell=[[3.657106, 0.0, 0.0], [1.828554, 3.167147, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  This might lead to unexpected results.                                 
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
WARNING  atom_checks          check_if_primitive   |
 This might lead to unexpected results.
INFO     Calculating the following angles: 0, 10, 15, 20 in degree.             
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     algorithm            check_angles         |
 Calculating the following angles: 0, 10, 15, 20 in degree.
INFO     Using 12 OpenMP threads.                                               
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     algorithm            run                  |
 Using 12 OpenMP threads.
INFO     Running through 10240000 grid points...                                
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     algorithm            run                  |
 Running through 10240000 grid points...
INFO     Found 2 results.                                                       
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
INFO     algorithm            run                  |
 Found 2 results.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[72], line 4
      2 alg = CoincidenceAlgorithm(bottom, top)
      3 # we run the algorithm for a choice of parameters
----> 4 results = alg.run(Nmax=20,Nmin=0, angles = [0, 10, 15, 20], weight=0.5,
      5                   angle_stepsize=0.05,
      6                   tolerance=0.1,  # 设置公差
      7                   distance=3.0)

File [~/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py:375](http://127.0.0.1:8888/home/xqliu/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py#line=374), in CoincidenceAlgorithm.run(self, Nmax, Nmin, angles, angle_limits, angle_stepsize, tolerance, weight, distance, standardize, no_idealize, symprec, angle_tolerance, verbosity)
    372 else:
    373     logger.info("Found {:d} results.".format(len(results)))
--> 375 interfaces = [
    376     Interface(
    377         k,
    378         weight=weight,
    379         bottom_bond_lengths=self.bdl,
    380         top_bond_lengths=self.tbl,
    381     )
    382     for k in results
    383 ]
    384 return interfaces

File [~/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py:376](http://127.0.0.1:8888/home/xqliu/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py#line=375), in <listcomp>(.0)
    372 else:
    373     logger.info("Found {:d} results.".format(len(results)))
    375 interfaces = [
--> 376     Interface(
    377         k,
    378         weight=weight,
    379         bottom_bond_lengths=self.bdl,
    380         top_bond_lengths=self.tbl,
    381     )
    382     for k in results
    383 ]
    384 return interfaces

File [~/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py:190](http://127.0.0.1:8888/home/xqliu/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py#line=189), in Interface.__init__(self, interface, weight, **kwargs)
    188 self.bbl = kwargs.get("bottom_bond_lengths", None)
    189 self.tbl = kwargs.get("top_bond_lengths", None)
--> 190 self._bonds, self._bond_lengths = get_bond_data(self.stack)

File [~/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py:123](http://127.0.0.1:8888/home/xqliu/anaconda3/envs/hetbuilder/lib/python3.11/site-packages/hetbuilder/algorithm.py#line=122), in get_bond_data(atoms, return_bonds)
    121         i += 1
    122         if i == 3:
--> 123             raise Exception(
    124                 "Could not find all species in the subquery. This should not happen."
    125             )
    127     atoms = subatoms
    129 pairs = list(combinations_with_replacement(symbs, 2))

**Exception: Could not find all species in the subquery. This should not happen.**

Why is this an error? How can I solve it?

**Comment by hongyi-zhao** [comment]
Could you please use [my forked and enhanced version](https://github.com/hongyi-zhao/hetbuilder) to do the test?

**Comment by ShiQiaoL** [comment]
> Could you please use [my forked and enhanced version](https://github.com/hongyi-zhao/hetbuilder) to do the test?

Thanks，I'll test it right away。

**Comment by ShiQiaoL** [comment]
> Could you please use [my forked and enhanced version](https://github.com/hongyi-zhao/hetbuilder) to do the test?

I used your [new version](https://github.com/hongyi-zhao/hetbuilder）) and had the same problem？Do you have any other good suggestions?

**Comment by hongyi-zhao** [comment]
Fixed in [this commit](https://github.com/hongyi-zhao/hetbuilder/commit/2c5d8aa5617a064ddb04a2af75d35213682d9b85). Please recheck with your example below:

[test-err.zip](https://github.com/user-attachments/files/15895580/test-err.zip)

**Comment by ShiQiaoL** [comment]
> Fixed in [this commit](https://github.com/hongyi-zhao/hetbuilder/commit/2c5d8aa5617a064ddb04a2af75d35213682d9b85). Please recheck with your example below:
> 
> [test-err.zip](https://github.com/user-attachments/files/15895580/test-err.zip)

thanks, this issue has been solved.
