### ISSUE TITLE
undefined symbol error

### ISSUE THREAD

**Issue by RinuKulkarni** [romankempt/hetbuilder#3]
miniconda4/envs/hetbuilder/lib/python3.9/site-packages/hetbuilder/hetbuilder_backend.cpython-39-x86_64-linux-gnu.so: undefined symbol: spgat_standardize_cell

**Comment by romankempt** [comment]
The undefined symbol error is a runtime linking error which I can't reproduce. Other people have similar issues with pybind11 (https://github.com/pybind/pybind11/issues), e.g., https://github.com/pybind/pybind11/issues/3623.

Unfortunately, I currently have no idea how to solve it...

**Comment by RinuKulkarni** [comment]
Hi,
    May I know the architecture of your machine. I tried everything.  
Hetbuilder is installed successfully but when I do hetbuilder --help I  
get the error.


Regards,
Ramya
Quoting Roman Kempt ***@***.***>:

**Comment by romankempt** [comment]
Lenovo thinkpad T14 with intel cpus. I'm running everything in WSL. Here is a list of my installed conda modules where the installation works without any issues.

[hetbuilder_list.txt](https://github.com/romankempt/hetbuilder/files/8529504/hetbuilder_list.txt)

I do not know what causes this error. It seems to be a very subtle problem (perhaps something with RPATH). I'm checking out docker, but till I understand how that works it might take some time.

**Comment by romankempt** [comment]
should now be resolved
