### ISSUE TITLE
Construct twisted bilayer graphene with hetbuilder.

### ISSUE THREAD

**Issue by hongyi-zhao** [romankempt/hetbuilder#8]
I try to construct twisted bilayer graphene around the magic angle, aka, 1.1 degree, as described [here](https://en.wikipedia.org/wiki/Twistronics#Superconduction_and_Insulation) and page 3 in this [paper](https://arxiv.org/pdf/1802.00553.pdf):

![image](https://github.com/romankempt/hetbuilder/assets/11155854/a8f5ab0d-e1fd-40b4-aaf3-58b3fad6adbd)
![image](https://github.com/romankempt/hetbuilder/assets/11155854/1520145b-665e-44c8-8752-2e3a63c086cb)

For this purpose, I tried the following command:
```shell
(datasci) werner@X10DAi:~/Public/repo/github.com/romankempt/tutorial/mytest$ hetbuilder build -t 0.1 -as 0.1 -al 1 1.5 graphene.xyz graphene.xyz 
INFO     Building heterostructures from C2 and C2.                                                                                                               
WARNING  It seems that the structure Atoms(symbols='C2', pbc=True, cell=[[1.23, -2.13042249, 0.0], [1.23, 2.13042249, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  This might lead to unexpected results.                                                                                                                  
WARNING  It seems that the structure Atoms(symbols='C2', pbc=True, cell=[[1.23, -2.13042249, 0.0], [1.23, 2.13042249, 0.0], [0.0, 0.0, 100.0]]) is not primitive.
WARNING  This might lead to unexpected results.                                                                                                                  
INFO     Searching 6 angles between 1.0 and 1.5 degree with a stepsize of 0.1 degree.                                                                            
INFO     Using 88 OpenMP threads.                                                                                                                                
INFO     Running through 960000 grid points...                                                                                                                   
	 Angle Search 	 	 [==================================================>] (100%)
	 Coincidence Pairs 	 [==================================================>] (100%)
	 Building Supercells 	 [==================================================>] (100%)
	 Removing Duplicates 	 [==================================================>] (100%)
INFO     Found 4 results.                                                                                                                                              
```
But all the above 4 found [`bilayer graphene`](https://en.wikipedia.org/wiki/Bilayer_graphene)s have 0.0% deformations and no twisted angles were found between the two layers consisting of the corresponding heterostructures:

![image](https://github.com/romankempt/hetbuilder/assets/11155854/1b1cbf6d-5f24-45b9-b27b-d7684ffe0513)
![image](https://github.com/romankempt/hetbuilder/assets/11155854/85c666e4-0a0f-4e37-a7d2-85bacb18e96d)
![image](https://github.com/romankempt/hetbuilder/assets/11155854/77da78e2-e6f6-4e91-8c69-b8265c7d430c)
![image](https://github.com/romankempt/hetbuilder/assets/11155854/0d715bb7-be45-4480-8645-f766b3c21d1f)

Any comments and explanations will be helpful.

Regards,
Zhao

**Comment by romankempt** [comment]
The supercells the algorithm finds depend crucially on the input lattice parameters. To reproduce the paper, you need exactly the same starting structures.

To search for a specific angle, use the `--angle` option.

The magic angle supercell of graphene is extremely large with something like 10000 atoms. This is not the case that hetbuilder was designed for. You might find matching supercells if you search in the right range of maximum and minimum translations (please see the docs), but with so many atoms, the ASE parts and the matplotlib GUI will simply not work. Hetbuilder was designed to find small coincidence unit cells for interfaces, not micrometer-scale twist angle structures. Also, for such large systems, the idea of a unit cell no longer works because the layers wrinkle.
